# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Ragazzo
description: Domain Driven Design, Service Oriented Architecture, Event Driven Architecture, Distributed Systems
url: "http://ragazzo.github.io"
github_username:  Ragazzo
highlighter: rouge
markdown: kramdown
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-feed
