title: Mark Ragazzo
description: Domain Driven Design, Service Oriented Architecture, Event Driven Architecture, Distributed Systems
url: "http://ragazzo.github.io"
github_username:  Ragazzo
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
paginate: 5
gems:
  - jekyll-paginate
  - jekyll-feed
